# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Github V2
email: mike.pan@wework.com
description: >- # this means to ignore newlines until "baseurl:"
  Github V2
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ui-v2
permalink: /posts/:year/:month/:day/:title

markdown: kramdown
theme: minima
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme

highlighter: rouge
include:
  - _redirects
exclude:
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
timezone: Asia/Shanghai
host: '0.0.0.0'
defaults:
  - scope:
      type: posts
      path: ''
    values:
      layout: post
      sitemap: true

feed:
  path: feed.xml
